#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/mizemoon/mizemoon /usr/bin/mizemoon
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/mizemoon.service ]; then
			rm /etc/systemd/system/mizemoon.service /usr/lib/systemd/system/mizemoon.service /usr/lib/systemd/user/mizemoon.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/mizemoon/files/systemd/mizemoon.service /usr/lib/systemd/system/mizemoon.service
		# try fix error in Ubuntu 18.04
		# Failed to reload mizemoon.service: Unit mizemoon.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/mizemoon.service:10: Executable path is not absolute: pkill -f "mizemoon --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/mizemoon.service
		fi
		systemctl daemon-reload
		systemctl enable mizemoon
		systemctl start mizemoon
	fi
fi
